#ifndef BLACKOUT_DETECT_O_MATIC_TEST_POWER_CHANGE_EVENT_PROCESSOR_H
#define BLACKOUT_DETECT_O_MATIC_TEST_POWER_CHANGE_EVENT_PROCESSOR_H

#include <unity.h>
#include <Arduino.h>

#include "SystemStatus.h"
#include "PowerChangeEventProcessor.h"

#endif //BLACKOUT_DETECT_O_MATIC_TEST_POWER_CHANGE_EVENT_PROCESSOR_H
