#ifndef BLACKOUT_DETECT_O_MATIC_TEST_UNIX_TIME_WITH_MILLISECONDS_H
#define BLACKOUT_DETECT_O_MATIC_TEST_UNIX_TIME_WITH_MILLISECONDS_H

#include <Arduino.h>
#include <unity.h>

#include "UnixTimeWithMilliSeconds.h"

#endif //BLACKOUT_DETECT_O_MATIC_TEST_UNIX_TIME_WITH_MILLISECONDS_H
